server:
  port: 8888
    
spring:
  profiles:
    active:
    - native
    
  cloud:
    config:
      server:
        native:
          search-locations:
          - /Users/PedroOliveira/Documents/projetos_java_cloud/config-repo
